import { LocalJustificationInfo, ILocalJustificationInfo } from "./LocalJustificationInfo";
import { LlmMessageSectionInfo, ILlmMessageSectionInfo } from "./LlmMessageSectionInfo";


export interface IBaseAiOptimizationLlmResponseElementItem   {
        
        /** type of element */
        type?: string | undefined

    [key: string]: any;

    }

export class BaseAiOptimizationLlmResponseElementItem  implements IBaseAiOptimizationLlmResponseElementItem {

    
    /** type of element */

    type?: string | undefined;

    [key: string]: any;


    protected discriminator: string;

    constructor(data?: IBaseAiOptimizationLlmResponseElementItem) {

    if (data) {
        for (var property in data) {
            if (data.hasOwnProperty(property))
                (<any>this)[property] = (<any>data)[property];
        }
    }

    this.discriminator = "BaseSerpElementItem";

    }

    init(data?: any) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
            this.type = data["type"];
        }
    }

    static fromJS(data: any): BaseAiOptimizationLlmResponseElementItem {
        data = typeof data === 'object' ? data : {};

        if (data["type"] === "reasoning") {

            let result = new ReasoningAiOptimizationLlmResponseElementItem();
            result.init(data);
            return result;
        }
        if (data["type"] === "message") {

            let result = new MessageAiOptimizationLlmResponseElementItem();
            result.init(data);
            return result;
        }

        let result = new BaseAiOptimizationLlmResponseElementItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};

        
        
        data["type"] = this.type;
        return data;
    }
}

 
export interface IReasoningAiOptimizationLlmResponseElementItem  extends IBaseAiOptimizationLlmResponseElementItem    {
        
        /** reasoning chain sections
array of objects containing the reasoning chain sections generated by the LLM */
        sections?: LocalJustificationInfo[] | undefined

    [key: string]: any;

    }

export class ReasoningAiOptimizationLlmResponseElementItem  extends BaseAiOptimizationLlmResponseElementItem   implements IReasoningAiOptimizationLlmResponseElementItem {

    
    /** reasoning chain sections
array of objects containing the reasoning chain sections generated by the LLM */

    sections?: LocalJustificationInfo[] | undefined;

    [key: string]: any;


    constructor(data?: IReasoningAiOptimizationLlmResponseElementItem) {
    super(data);

    }

    init(data?: any) {
        super.init(data);
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
            if (Array.isArray(data["sections"])) {
                this.sections = [];
                for (let item of data["sections"]) {
                    this.sections.push(LocalJustificationInfo.fromJS(item));
                }
            }
        }
    }

    static fromJS(data: any): ReasoningAiOptimizationLlmResponseElementItem {
        data = typeof data === 'object' ? data : {};


        let result = new ReasoningAiOptimizationLlmResponseElementItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};

         
        super.toJSON(data);
        
        
        data["sections"] = null;
        if (Array.isArray(this.sections)) {
            data["sections"] = [];
            for (let item of this.sections) {
                if (item && typeof item.toJSON === "function") {
                    data["sections"].push(item?.toJSON());
                }
            }
        }
        return data;
    }
}

 
export interface IMessageAiOptimizationLlmResponseElementItem  extends IBaseAiOptimizationLlmResponseElementItem    {
        
        /** reasoning chain sections
array of objects containing the reasoning chain sections generated by the LLM */
        sections?: LlmMessageSectionInfo[] | undefined

    [key: string]: any;

    }

export class MessageAiOptimizationLlmResponseElementItem  extends BaseAiOptimizationLlmResponseElementItem   implements IMessageAiOptimizationLlmResponseElementItem {

    
    /** reasoning chain sections
array of objects containing the reasoning chain sections generated by the LLM */

    sections?: LlmMessageSectionInfo[] | undefined;

    [key: string]: any;


    constructor(data?: IMessageAiOptimizationLlmResponseElementItem) {
    super(data);

    }

    init(data?: any) {
        super.init(data);
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
            if (Array.isArray(data["sections"])) {
                this.sections = [];
                for (let item of data["sections"]) {
                    this.sections.push(LlmMessageSectionInfo.fromJS(item));
                }
            }
        }
    }

    static fromJS(data: any): MessageAiOptimizationLlmResponseElementItem {
        data = typeof data === 'object' ? data : {};


        let result = new MessageAiOptimizationLlmResponseElementItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};

         
        super.toJSON(data);
        
        
        data["sections"] = null;
        if (Array.isArray(this.sections)) {
            data["sections"] = [];
            for (let item of this.sections) {
                if (item && typeof item.toJSON === "function") {
                    data["sections"].push(item?.toJSON());
                }
            }
        }
        return data;
    }
}