export interface ISerpAiSummaryItem   {
        
        /** *generated summary* summary generated by the AI model according to the parameters specified in the request */
        summary?: string | undefined

    [key: string]: any;

    }

export class SerpAiSummaryItem  implements ISerpAiSummaryItem {

    
    /** *generated summary* summary generated by the AI model according to the parameters specified in the request */

    summary?: string | undefined;

    [key: string]: any;


    constructor(data?: ISerpAiSummaryItem) {

    if (data) {
        for (var property in data) {
            if (data.hasOwnProperty(property))
                (<any>this)[property] = (<any>data)[property];
        }
    }

    }

    init(data?: any) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    this[property] = data[property];
            }
            this.summary = data["summary"];
        }
    }

    static fromJS(data: any): SerpAiSummaryItem {
        data = typeof data === 'object' ? data : {};


        let result = new SerpAiSummaryItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};

        
        
        data["summary"] = this.summary;
        return data;
    }
}